runtime: java
env: flex

handlers:
  - url: /.*
    script: this field is required, but ignored

# [START gae_flex_pubsub_yaml]
env_variables:
  PUBSUB_TOPIC: CREATE
  # This token is used to verify that requests originate from your
  # application. It can be any sufficiently random string.
  PUBSUB_VERIFICATION_TOKEN: 1234
# [END gae_flex_pubsub_yaml]